local M = {}

local defaults = {
  -- icons used by other plugins
  icons = {
    misc = {
      breadcrumb = "󰄾",
      separator = "󱦰",
      group = "󰐕",
      ellipsis = "󰇘 ",
    },
    ft = {
      octo = " ",
    },
    dap = {
      Stopped = "",
      Breakpoint = "",
      BreakpointCondition = "",
      BreakpointRejected = "",
      LogPoint = "",
    },
    dapui = {
      controls = {
        pause = "",
        play = "",
        step_into = "",
        step_over = "",
        step_out = "",
        step_back = "",
        run_last = "",
        terminate = "",
        disconnect = "",
      },
      expanded = "",
      collapsed = "",
      current_frame = "",
    },
    diagnostics = {
      [vim.diagnostic.severity.ERROR] = " ",
      [vim.diagnostic.severity.WARN] = " ",
      [vim.diagnostic.severity.HINT] = " ",
      [vim.diagnostic.severity.INFO] = " ",
    },
    git = {
      added = " ",
      modified = " ",
      removed = " ",
    },
    lazynvim = {
      cmd = "",
      config = "",
      debug = "",
      event = "",
      favorite = "",
      ft = "",
      init = "",
      import = "",
      keys = "",
      lazy = "",
      loaded = "",
      not_loaded = "",
      plugin = "",
      runtime = "",
      require = "",
      source = "",
      start = "",
      task = "",
      list = {
        "",
        "",
        "",
        "",
        "",
      },
    },
    kinds = {
      Array = " ",
      Boolean = " ",
      Class = " ",
      Codeium = " ",
      Color = " ",
      Control = " ",
      Collapsed = " ",
      Constant = " ",
      Constructor = " ",
      Copilot = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Folder = " ",
      Function = " ",
      Interface = " ",
      Key = " ",
      Keyword = " ",
      Method = " ",
      Module = " ",
      Namespace = " ",
      Null = " ",
      Number = " ",
      Object = " ",
      Operator = " ",
      Package = " ",
      Property = " ",
      Reference = " ",
      Snippet = " ",
      String = " ",
      Struct = " ",
      Supermaven = " ",
      TabNine = " ",
      Text = " ",
      TypeParameter = " ",
      Unit = " ",
      Value = " ",
      Variable = " ",
    },
    keys = {
      Up = "",
      Down = "",
      Left = "",
      Right = "",
      C = "󰘴",
      M = "󰘵",
      D = "󰘳",
      S = "󰘶",
      CR = "󰌑",
      Esc = "󱊷",
      ScrollWheelDown = "󱕐",
      ScrollWheelUp = "󱕑",
      NL = "󰌑",
      BS = "󰌍",
      Space = "󱁐",
      Tab = "󰌒",
      F1 = "󱊫",
      F2 = "󱊬",
      F3 = "󱊭",
      F4 = "󱊮",
      F5 = "󱊯",
      F6 = "󱊰",
      F7 = "󱊱",
      F8 = "󱊲",
      F9 = "󱊳",
      F10 = "󱊴",
      F11 = "󱊵",
      F12 = "󱊶",
    },
  },
  rainbow = {
    "RainbowRed",
    "RainbowYellow",
    "RainbowBlue",
    "RainbowOrange",
    "RainbowGreen",
    "RainbowViolet",
    "RainbowCyan",
  },
  rainbow_hl = {
    ["RainbowRed"] = { fg = "#E06C75" },
    ["RainbowYellow"] = { fg = "#E5C07B" },
    ["RainbowBlue"] = { fg = "#61AFEF" },
    ["RainbowOrange"] = { fg = "#D19A66" },
    ["RainbowGreen"] = { fg = "#98C379" },
    ["RainbowViolet"] = { fg = "#C678DD" },
    ["RainbowCyan"] = { fg = "#56B6C2" },
  },
}

-- https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings
function M.has_words_before()
  unpack = unpack or table.unpack
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
end

setmetatable(M, {
  __index = function(_, key) return vim.deepcopy(defaults)[key] end,
})

return M
